### ISSUE TITLE
Ошибка парсинга datetime если он уже нужного типа

### ISSUE THREAD

**Issue by tarrac79** [Tishka17/dataclass_factory#45]
```python
from dataclasses import dataclass
from dataclass_factory import Factory
from datetime import datetime


@dataclass()
class Traffic:
    time: datetime
    rx: int
    tx: int


if __name__ == '__main__':
    dict_traff = {
        'time': datetime(2019, 12, 1, 1, 20, 13),
        'rx': 10,
        'tx': 15
    }

    factory = Factory()
    traff: Traffic = factory.load(dict_traff, Traffic)
    print(factory.dump(traff))
    
    
```

Ошибка:
```
Traceback (most recent call last):
  File "E:/NMS/NMSProgect/modules/traffic.py", line 24, in <module>
    traff: Traffic = factory.load(dict_traff, Traffic)
  File "E:\NMS\lib\site-packages\dataclass_factory\factory.py", line 94, in load
    return self.parser(class_)(data)
  File "E:\NMS\lib\site-packages\dataclass_factory\parsers.py", line 139, in dataclass_parser
    for field, name, parser in field_info
  File "E:\NMS\lib\site-packages\dataclass_factory\parsers.py", line 140, in <dictcomp>
    if name in data
  File "E:\NMS\lib\site-packages\dataclass_factory\parsers.py", line 186, in class_parser
    k: parser(data.get(k)) for k, parser in parsers.items() if k in data
  File "E:\NMS\lib\site-packages\dataclass_factory\parsers.py", line 186, in <dictcomp>
    k: parser(data.get(k)) for k, parser in parsers.items() if k in data
TypeError: argument of type 'datetime.datetime' is not iterable
```

**Comment by Tishka17** [comment]
```
def parser(data):
     if not isinstance(data, T):
            raise TypeError()
     return data
```

Добавить в schema_helpers схему с таким парсером.

**Comment by Tishka17** [comment]
Use ClsCheckSchema from `schema_helpers`
